name: Auto cancel
on:
  push:
    paths:
      - '.github/workflows/auto_cancel.yml'

concurrency:
  group: ${{ github.workflow }}-${{github.ref}} # 同じワークフローかつ同じブランチの場合、cancel-in-progressを実行する。
  cancel-in-progress: true # 同一のワークフローが多重起動した場合は、古い方のワークフローを停止し、新しい方のワークフローを起動する

jobs:
  sleep:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_NAME: ${{github.workflow}}
    steps:
      - run: echo "${WORKFLOW_NAME}"
      - run: sleep 120
