name: Change shell
on:
  push:
    paths:
      - '.github/workflows/change_shell.yml'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: bash # ステップごとにシェルを指定できる
        run: echo "${SHELL}"
      - shell: python
        run: |
          import os
          print(os.environ['PATH'])
