name: Conditions workflow
on:
  push:
    paths:
      - '.github/workflows/conditions_workflow.yml'

jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat' }}
    runs-on: ubuntu-latest # githubアカウントがoctocatの場合のみ以下を実行する
    steps:
      - run: echo "Hello"  
