name: Conditions
on:
  push:
    paths:
      - '.github/workflows/condition.yml'

jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello" 
        if: ${{contains(github.run_id, '1')}}
         