name: Context
on:
  push:
    paths:
      - '.github/workflows/context.yml'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"  # githubのコンテキスト機能を使ってワークフローの実行者を取得する（コンテキストは直接シェルに埋め込まないこと。環境変数経由でコンテキストを渡すこと※　アンチパターン）
