name: Log group
on:
  push:
    paths:
      - .github/workflows/log_group.yml'

jobs:
  log_group:
    runs-on: ubuntu-latest
	# ログの表示をロググループでまとめる
    steps:
      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup"
